spring:
  application:
    name: social-media

  datasource:
    url: jdbc:mysql://localhost:3306/socialmedia
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
#    url: jdbc:mysql://revature-social-media-db.c9auc2sc0y0s.us-east-2.rds.amazonaws.com:3306/socialmedia
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: admin
#    password: aSl1NQI^SyaHOT5
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
#  sql:
#    init:
#      mode: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
